export interface ExecutiveMember {
    name: string;
    designation: string;
}

export const executiveMembers: ExecutiveMember[] = [
    { name: "Janab Yunus Kazia", designation: "President" },
    { name: "Janab Mohammed Sadique Pillur", designation: "Vice President I" },
    { name: "Janab Dr. Zubair Kola", designation: "Vice President II" },
    { name: "Janab Mohammed Ishaque Shabandri", designation: "General Secretary" },
    { name: "Janab Mohammed Ismail Jukaku", designation: "Additional General Secretary" },
    { name: "Janab Syed Ahmed Parvez S.M", designation: "Finance Secretary" },
    { name: "Janab Syed Hashim S J", designation: "Works Committee Secretary" },
    { name: "Janab Mohammed Ansar Damdaabu", designation: "IT Secretary" },
    { name: "Janab Mohammed Ansar Damdaabu", designation: "Secretary, AITM Board" },
    { name: "Janab Mohammed Aheed Mohtesham", designation: "Secretary, AIMCA Board" },
    { name: "Janab Faiyaz Ahmed Kola", designation: "Secretary, Degree & PU College Board" },
    { name: "Janab Sadullah Ruknuddin", designation: "Secretary, High School Board" },
    { name: "Janab Mohammed Tanveer Kasarkod", designation: "Secretary, Primary Board" },
    { name: "Janab Abdul Hameed Athar Ruknuddin", designation: "Secretary, Deeniyat Board" },
    { name: "Janab Abdul Haseeb Kadli", designation: "Executive Member" },
    { name: "Janab Abdul Wajid Kola", designation: "Executive Member" },
    { name: "Janab Abdus Sami Kola", designation: "Executive Member" },
    { name: "Janab Afaque Kola", designation: "Executive Member (Advocate)" },
    { name: "Janab Burhan K.M Kokari", designation: "Executive Member" },
    { name: "Janab Dr. Mohammed Zaheer Kola", designation: "Executive Member" },
    { name: "Janab Enayatullah Shabandri", designation: "Executive Member" },
    { name: "Janab Imtiyaz Hussain Ruknuddin", designation: "Executive Member" },
    { name: "Janab Irshad Ahmed Siddiqui", designation: "Executive Member" },
    { name: "Janab Ismail Siddique", designation: "Executive Member" },
    { name: "Janab Mohammed Ameen Ruknuddin", designation: "Executive Member" },
    { name: "Janab Mohammed Asaf Damudi", designation: "Executive Member" },
    { name: "Janab Mohammed Irshad Gawai", designation: "Executive Member" },
    { name: "Janab Mohammed Ismail Jubapu", designation: "Executive Member" },
    { name: "Janab Mohammed Meeran Ismailji", designation: "Executive Member (Patron)" },
    { name: "Janab Mohd Mubasshir Hussain Hallare", designation: "Executive Member" },
    { name: "Janab Mohammed Muzzammil Kazia", designation: "Executive Member" },
    { name: "Janab Mohammed Zakariya Shingeri", designation: "Executive Member (Patron)" },
    { name: "Janab Mohammed Zubair Armar", designation: "Executive Member" },
    { name: "Janab Mushtaque K.M", designation: "Executive Member" },
    { name: "Janab Rameez Kola", designation: "Executive Member" },
    { name: "Janab Riyaz M.J", designation: "Executive Member" },
    { name: "Janab S.M Syed Zakir", designation: "Executive Member" },
    { name: "Janab Shafi Master Shabandri Patel", designation: "Executive Member" },
    { name: "Janab Syed Hassan Saqqaf S.M", designation: "Executive Member (Patron)" },
    { name: "Janab Syed Ibrahim Azhar Barmawer", designation: "Executive Member" },
    { name: "Janab Abdul Mueed Kadli (Bangalore)", designation: "Executive Member" },
    { name: "Janab Muddassir Ekkeri (Bangalore)", designation: "Executive Member" },
    { name: "Janab Saifan Shingeri (Bangalore)", designation: "Executive Member" },
    { name: "Janab Mohammed Hashim Mohtesham (Calcutta)", designation: "Executive Member" },
    { name: "Janab Abdur Rasheed Mohtesham (Chennai)", designation: "Executive Member" },
    { name: "Janab Al-Haj Mohsin Shabandri (Chennai)", designation: "Executive Member (Patron)" },
    { name: "Janab Syed Mohiddin S.M Market (Chennai)", designation: "Executive Member" },
    { name: "Janab Zaheer Bota (Coorg)", designation: "Executive Member" },
    { name: "Janab Atif Shabandri Patel (Kerala)", designation: "Executive Member" },
    { name: "Janab Fayyaz Ahmed Misbah (Kerala)", designation: "Executive Member" },
    { name: "Janab Mohammed Faizan Lanka (Kerala)", designation: "Executive Member" },
    { name: "Janab Aftab Kola (Mangalore)", designation: "Executive Member" },
    { name: "Janab Arshad S.M (Mangalore)", designation: "Executive Member" },
    { name: "Janab Abdus Salam Damudi (Mumbai)", designation: "Executive Member" },
    { name: "Janab Adil Nagarmat (Mumbai)", designation: "Executive Member" },
    { name: "Janab Bilal Ahmed Ruknuddin (Vijayawada)", designation: "Executive Member" },
    { name: "Janab Fawwaz Mohtesham (Vijayawada)", designation: "Executive Member" },
    { name: "Janab Fayyaz Kola (Doha, Qatar)", designation: "Executive Member" },
    { name: "Janab Shahriyar Ahmed Khateeb (Dubai)", designation: "Executive Member" },
    { name: "Janab Jailani Mohtesham (Dubai)", designation: "Executive Member" },
    { name: "Janab Mohammed Yasir Kashimji (Dubai)", designation: "Executive Member" },
    { name: "JanabZubair Musbah (Dubai)", designation: "Executive Member" },
    { name: "Janab Taha Muallim (Dubai)", designation: "Executive Member" },
    { name: "Janab Syed Ali Sufyan S.M (Dubai)", designation: "Executive Member" },
    { name: "Janab Syed Afzal S.M (Dubai)", designation: "Executive Member" },
    { name: "Janab Shamsuddin Zia Damda Kallagar (Dubai)", designation: "Executive Member" },
    { name: "Janab Imdadullah Peshmam (Dubai)", designation: "Executive Member" },
    { name: "Janab Mohiddin Amber Kobatte (Dubai)", designation: "Executive Member" },
    { name: "Janab Ashfaque Sada (Dubai)", designation: "Executive Member" },
    { name: "Janab Atiqurrahman Muniri (Dubai)", designation: "Executive Member" },
    { name: "Dr. Syed Khaleelurrahman S.M (Dubai)", designation: "Executive Member (Patron)" },
    { name: "Dr. Mohammed Ismail Kazia (Dubai)", designation: "Executive Member (Patron)" },
    { name: "Janab Mohammed Ibrahim Kazia (Dubai)", designation: "Executive Member (Patron)" },
    { name: "Janab Ashraf Ali Musbah (Abu Dhabi)", designation: "Executive Member" },
    { name: "Janab Mohiddin Irshad Siddiqua (KSA EP)", designation: "Executive Member" },
    { name: "Janab Farooque Shabandri Patel (KSA EP)", designation: "Executive Member" },
    { name: "Janab Mohammed Miran Javeed Kola (KSA EP)", designation: "Executive Member" },
    { name: "Janab Mohammed Nayyem Ekkeri (KSA EP)", designation: "Executive Member" },
    { name: "Janab Arshad Hassan Kadli (KSA EP)", designation: "Executive Member" },
    { name: "Janab Abdus Salam Damda Abu (KSA JED)", designation: "Executive Member" },
    { name: "Janab Mohammed Yasin Askeri (KSA JED)", designation: "Executive Member" },
    { name: "Janab Mohammed Ammar Kazia (KSA RYD)", designation: "Executive Member" },
    { name: "Janab Abdul Aleem Kazia (KSA RYD)", designation: "Executive Member (Patron)" },
    { name: "Janab Mohammed Zimad Ruknuddin (KSA Yanbu)", designation: "Executive Member" },
    { name: "Janab Altaf Musbah (Bahrain)", designation: "Executive Member" },
    { name: "Janab Mukhtar M.J (Kuwait)", designation: "Executive Member" },
    { name: "Janab Syed Hussain Barmawar (Muscat)", designation: "Executive Member" },
    { name: "Janab Abdul Bari S.P (Muscat)", designation: "Executive Member" },
    { name: "Janab Yunus Shabandri (Kerala)", designation: "Non Executive Member" }
];
