export const aitmBoardMembers = [
    { name: "Janab Yunus Kazia", designation: "President" },
    { name: "Janab Mohammed Sadique Pillur", designation: "Vice President I" },
    { name: "Janab Dr. Zubair Kola", designation: "Vice President II" },
    { name: "Janab Mohammed Ishaque Shabandri", designation: "General Secretary" },
    { name: "Janab Mohammed Ismail Jukaku", designation: "Additional General Secretary" },
    { name: "Janab Syed Ahmed Parvez S.M", designation: "Finance Secretary" },
    { name: "Janab Syed Hashim S J", designation: "Secretary, Works Committee" },
    { name: "Janab Mohammed Ansar Damdaabu", designation: "Secretary, IT, AITM Board" },
    { name: "Janab Mohammed Aheed Mohtesham", designation: "Secretary, AIMCA, ACE Board" },
    { name: "Janab Faiyaz Ahmed Kola", designation: "Secretary, Degree & PU College Board" },
    { name: "Janab Sadullah Ruknuddin", designation: "Secretary, High School Board" },
    { name: "Janab Afaque Mohtesham", designation: "Secretary, Primary Board" },
    { name: "Janab Abdul Hameed Athar Ruknuddin", designation: "Secretary, Deeniyat Board" },
    { name: "Janab Abdul Haseeb Kadli", designation: "Member (Patron)" },
    { name: "Janab Abdul Wajid Kola", designation: "Member" },
    { name: "Janab Ismail Siddique", designation: "Member" },
    { name: "Janab Mohammed Ismail Jubapu", designation: "Member" },
    { name: "Janab Mohammed Faizan Lanka", designation: "Member" },
    { name: "Janab Jailani Mohtesham", designation: "Member" },
    { name: "Arshad Hassan Kadli", designation: "Member" },
    { name: "Dr. Fazlur Rahman K", designation: "Principal (Ex officio Member)" }
];
