export const highSchoolBoardMembers = [
    { name: "Janab Yunus Kazia", designation: "President" },
    { name: "Janab Mohammed Sadique Pillur", designation: "Vice President I" },
    { name: "Janab Dr. Zubair Kola", designation: "Vice President II" },
    { name: "Janab Mohammed Ishaque Shabandri", designation: "General Secretary" },
    { name: "Janab Mohammed Ismail Jukaku", designation: "Additional General Secretary" },
    { name: "Janab Syed Ahmed Parvez S.M", designation: "Finance Secretary" },
    { name: "Janab Syed Hashim S J", designation: "Secretary, Works Committee" },
    { name: "Janab Mohammed Ansar Damdaabu", designation: "Secretary, IT, AITM Board" },
    { name: "Janab Mohammed Aheed Mohtesham", designation: "Secretary, AIMCA, ACE Board" },
    { name: "Janab Faiyaz Ahmed Kola", designation: "Secretary, Degree & PU College Board" },
    { name: "Janab Sadullah Ruknuddin", designation: "Secretary, High School Board" },
    { name: "Janab Afaque Mohtesham", designation: "Secretary, Primary Board" },
    { name: "Janab Abdul Hameed Athar Ruknuddin", designation: "Secretary, Deeniyat Board" },
    { name: "Janab Abdul Wajid Kola", designation: "Member" },
    { name: "Janab Irshad Ahmed Siddiqui", designation: "Member" },
    { name: "Janab Mohammed Mubasshir Hussain Hallare", designation: "Member" },
    { name: "Janab Syed Ibrahim Azhar Barmawer", designation: "Member" },
    { name: "Janab Aftab Kola", designation: "Member" },
    { name: "Janab Syed Afzal S.M", designation: "Member" },
    { name: "Janab Mohammed Nayyem Ekkeri", designation: "Member" }
];
